version: "3"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    entrypoint: sh ./run.sh
    depends_on:
      - db

  db:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - ./rundb.sh:/docker-entrypoint-initdb.d/rundb.sh
      - pgdb_data:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: on-failure

volumes:
  pgdb_data: